### ISSUE TITLE
Reliance on typing breaks 3.7

### ISSUE THREAD

**Issue by shughes-uk** [joseph-roitman/pytest-snapshot#15]
This project depends on the back port of the `typing` module. I assume to prevent breakages with 2.7.

`Typing` is an incomplete back port and does not contain everything in the 3.7 version of `typing', breaking packages that do rely on them. PyInstaller 3.6 is an example of this.

To prevent this this library should only depend on `typing` from pypi for versions of python <3.5 .

Some references
https://pypi.org/project/typing/
https://fernandomc.com/posts/issues-with-typing-python-3/
https://stackoverflow.com/questions/57383625/why-is-there-an-error-installing-the-pyinstaller

**Comment by joseph-roitman** [comment]
Thanks for the heads up, its fixed in v0.4.1.
