### ISSUE TITLE
[feature request] a mode which fails if snapshot file isn't already present

### ISSUE THREAD

**Issue by kvudata** [joseph-roitman/pytest-snapshot#21]
The current default behavior seems to be to generate a new snapshot if one hasn't been recorded yet.
It would be useful if we had the option to enforce the presence of a snapshot instead of automatically creating one (e.g. via CLI flag) - for example this could be used when running snapshot tests on CI to ensure that the snapshot has been correctly committed to the repo.

**Comment by joseph-roitman** [comment]
The default behaviour is to not modify the snapshots in any way and to only fail invalid tests.
The snapshot will be created only if you add the `--snapshot-update` flag.
Did you see something else happening?

**Comment by kvudata** [comment]
Ah I'm sorry, this is embarassing, I mixed up this repo with https://github.com/syrusakbary/snapshottest/
