### ISSUE TITLE
0.6.0 Breaking multi-line comparisons in Windows styled files

### ISSUE THREAD

**Issue by mshafer-NI** [joseph-roitman/pytest-snapshot#31]
New (breaking) behavior in 0.6.0 on Windows to only use Line Feeds.

Example way to reproduce:
* `git clone  https://github.com/mshafer-NI/reproduce_problem_upgrading_pytest_snapshot`
* `poetry install` # will install 0.5.0
* `poetry run pytest` # passes
* Edit pyproject.toml to list `0.6.0` for `pytest-snapshot`
* `poetry lock`
* `poetry install`
* `poetry run pytest` # test fails

(if don't have poetry installed)
* `git clone  https://github.com/mshafer-NI/reproduce_problem_upgrading_pytest_snapshot`
* `python -m venv _env`
* `env\Scripts\activate`
* `pip install pytest pytest-snapshot==0.5.0`
* `pytest` # passes
* `pip isntall -U pytest-snapshot==0.6.0`
* `pytest` # fails

**Comment by joseph-roitman** [comment]
Thanks for the quick bug report. I mistakenly thought path.read_bytes().decode() was equivalent to path.read_text(), but read_text also modifies newlines. I will create a fix soon.

**Comment by joseph-roitman** [comment]
I fixed this in v0.6.1. Sorry for the bug and thanks again for the bug report.

**Comment by mshafer-NI** [comment]
Thank you for the quick response.
